#!/bin/bash
#
#This bash script copies all configurations in this repo to their respective locations

#home folder
cp -rvT ./home ~
#fonts
##install abeezee
curl -O https://www.fontsquirrel.com/fonts/download/abeezee
7z x abeezee
cd abeezee_FILES
mkdir -pv ~/.local/share/fonts
mv ABeeZee* ~/.local/share/fonts

#icons
##install papyrus
trizen -Sy papirus-icon-theme-git




#####ask what DE is being used and figure out how to apply things like font and theme automagically

##cleanup
cd ~
rm -rf abeezee*
rm -rf mpv
rm -rf conky
