#!/bin/bash
#
#This bash script copies all configurations in this repo to their respective locations

#home folder
cp ./home/.bash_profile ~/
cp ./home/.bashrc ~/

#fonts
##install abeezee
curl -O https://www.fontsquirrel.com/fonts/download/abeezee
7z x abeezee
cd abeezee_FILES
mkdir -pv ~/.local/share/fonts
mv ABeeZee* ~/.local/share/fonts

#icons
##install papyrus

#home
cp -r ./home ~


#conky
cp -r ./conky/conky.conf ~/.config/conky/

##cleanup
cd ~
rm -rf abeezee*
rm -rf mpv
rm -rf conky
